<?php

return [
  'icons' => [
    'exclamation-circle',
    'arrow-left',
    'arrow-right',
    'bell',
    'check-circle',
    'check',
    'chevron-down',
    'chevron-right',
    'pencil',
    'eye-slash',
    'eye',
    'heart',
    'home',
    'information-circle',
    'arrow-path',
    'lock-closed',
    'envelope',
    'bars-3',
    'minus',
    'phone',
    'plus',
    'magnifying-glass',
    'cog-6-tooth',
    'star',
    'trash',
    'lock-open',
    'user',
    'x-mark',
  ],
  'library' => 'https://heroicons.com',
];
